using Microsoft.Extensions.Options;
using Ovcuprim.Application.Abstractions;

namespace Ovcuprim.Infrastructure.Storage;

/// <summary>Development storage. Production swaps in an S3-compatible implementation behind the same interface.</summary>
public sealed class LocalFileStorage(IOptions<LocalFileStorageOptions> options) : IFileStorage
{
    private readonly LocalFileStorageOptions _options = options.Value;

    public async Task<string> SaveAsync(Stream content, string key, string contentType, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using var file = File.Create(path);
        await content.CopyToAsync(file, cancellationToken);

        return key;
    }

    public Task<Stream?> OpenAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);
        Stream? stream = File.Exists(path) ? File.OpenRead(path) : null;
        return Task.FromResult(stream);
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    public string GetPublicUrl(string key) => $"{_options.PublicBaseUrl.TrimEnd('/')}/{key.TrimStart('/')}";

    public Task<IReadOnlyList<string>> ListKeysAsync(
        string prefix, DateTimeOffset modifiedBefore, CancellationToken cancellationToken = default)
    {
        var root = Path.GetFullPath(_options.RootPath);
        var start = ResolvePath(prefix);

        if (!Directory.Exists(start))
        {
            return Task.FromResult<IReadOnlyList<string>>([]);
        }

        var keys = new List<string>();

        foreach (var path in Directory.EnumerateFiles(start, "*", SearchOption.AllDirectories))
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (File.GetLastWriteTimeUtc(path) >= modifiedBefore.UtcDateTime)
            {
                continue;
            }

            keys.Add(Path.GetRelativePath(root, path).Replace(Path.DirectorySeparatorChar, '/'));
        }

        return Task.FromResult<IReadOnlyList<string>>(keys);
    }

    /// <summary>Keys are generated by the application; this still refuses anything that escapes the root.</summary>
    private string ResolvePath(string key)
    {
        var root = Path.GetFullPath(_options.RootPath);
        var full = Path.GetFullPath(Path.Combine(root, key));

        if (!full.StartsWith(root, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("Storage key resolves outside the storage root.");
        }

        return full;
    }
}
