#!/usr/bin/env bash
#
# Regenerates the two nginx files derived from the CDN's published IP ranges.
#
#   /etc/nginx/conf.d/cloudflare-realip.conf   restores the true client address
#   /etc/nginx/conf.d/cloudflare-geo.conf      defines $cf_edge_ok for origin lock-down
#
# Both come from one fetch of the authoritative list, so they can never drift apart. The ranges
# change over time, which is why they are fetched here and never guessed or pinned by hand.
#
# Why real-IP restoration matters: the API partitions every rate limit on the address it ends up
# with, so if the edge is not resolved correctly they all collapse into a single bucket shared by
# every visitor — one caller can then lock out registration for everyone — and the audit trail
# records the proxy instead of the caller.
#
# Why the geo file and not plain `allow`/`deny`: ngx_http_realip_module rewrites $remote_addr in
# the post-read phase, which runs BEFORE ngx_http_access_module. An `allow <cdn ranges>` list would
# therefore be evaluated against the *restored* client address and reject every real visitor coming
# through the CDN. $realip_remote_addr keeps the original peer, so the geo map below tests the
# actual TCP peer — the CDN edge — which is what origin lock-down actually means.
#
# The geo file only DEFINES a variable; it restricts nothing on its own. Enforcement lives in the
# one vhost that tests it, so other sites on this host are untouched.
#
#   sudo deploy/nginx/update-cloudflare-nginx.sh
#   nginx -t && systemctl reload nginx
#
# Re-run periodically (a monthly timer is enough) so the list does not drift.
set -euo pipefail

REALIP_OUT="${1:-/etc/nginx/conf.d/cloudflare-realip.conf}"
GEO_OUT="${2:-/etc/nginx/conf.d/cloudflare-geo.conf}"
V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

TMP_REALIP="$(mktemp)"; TMP_GEO="$(mktemp)"
trap 'rm -f "$TMP_REALIP" "$TMP_GEO"' EXIT

fetch() { curl --fail --silent --show-error --max-time 20 "$1"; }

V4="$(fetch "$V4_URL")"
V6="$(fetch "$V6_URL")"

# A truncated or empty download must never produce a file that trusts nothing (breaking real-IP
# restoration) or, worse, one that locks every visitor out of the origin.
if [ -z "$V4" ] || [ -z "$V6" ]; then
  echo "refusing to write: empty range list from the upstream source" >&2
  exit 1
fi

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
  echo "# Generated by deploy/nginx/update-cloudflare-nginx.sh — do not edit by hand."
  echo "# Source: $V4_URL and $V6_URL"
  echo "# Fetched: $STAMP"
  echo
  while read -r c; do [ -n "$c" ] && echo "set_real_ip_from $c;"; done <<< "$V4"
  while read -r c; do [ -n "$c" ] && echo "set_real_ip_from $c;"; done <<< "$V6"
  echo
  echo "# Only consulted for peers listed above; ignored for any other client."
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP_REALIP"

{
  echo "# Generated by deploy/nginx/update-cloudflare-nginx.sh — do not edit by hand."
  echo "# Source: $V4_URL and $V6_URL"
  echo "# Fetched: $STAMP"
  echo "#"
  echo "# Defines a variable only — this file restricts nothing by itself. A vhost opts in with:"
  echo "#     if (\$cf_edge_ok = 0) { return 403; }"
  echo "#"
  echo "# Keyed on \$realip_remote_addr (the original TCP peer), not \$remote_addr, which realip has"
  echo "# already rewritten to the true client by the time this is evaluated."
  echo
  echo "geo \$realip_remote_addr \$cf_edge_ok {"
  echo "    default 0;"
  echo
  echo "    # Local health checks and maintenance from the host itself."
  echo "    127.0.0.1/32 1;"
  echo "    ::1/128 1;"
  echo
  while read -r c; do [ -n "$c" ] && echo "    $c 1;"; done <<< "$V4"
  while read -r c; do [ -n "$c" ] && echo "    $c 1;"; done <<< "$V6"
  echo "}"
} > "$TMP_GEO"

install -m 0644 "$TMP_REALIP" "$REALIP_OUT"
install -m 0644 "$TMP_GEO" "$GEO_OUT"
echo "wrote $REALIP_OUT ($(grep -c set_real_ip_from "$REALIP_OUT") ranges trusted)"
echo "wrote $GEO_OUT ($(grep -cE '^\s+[0-9a-fA-F:.]+/[0-9]+ 1;' "$GEO_OUT") entries allowed, including loopback)"
