#!/usr/bin/env bash
#
# Regenerates the host nginx snippet that restores the real client address when a CDN sits in front
# of this server.
#
# Why this exists, rather than a list of ranges committed to the repository: the API partitions
# every rate limit on the address it ends up with, so if the edge is not resolved correctly, all of
# them collapse into a single bucket shared by every visitor — one caller can then lock out
# registration for everyone, and the audit trail records the proxy instead of the caller. The
# ranges that make that resolution safe are published by the CDN and change over time, so they are
# fetched from the authoritative source here and never guessed or pinned by hand.
#
# The trust direction matters: CF-Connecting-IP is honoured ONLY when the connection itself arrives
# from one of these ranges. A request straight to the origin carrying a forged CF-Connecting-IP is
# ignored, because its peer address is not in the list.
#
#   sudo deploy/nginx/update-cloudflare-realip.sh
#   nginx -t && systemctl reload nginx
#
# Re-run it periodically (a monthly timer is enough) so the list does not drift.
set -euo pipefail

OUT="${1:-/etc/nginx/conf.d/cloudflare-realip.conf}"
V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch() {
  curl --fail --silent --show-error --max-time 20 "$1"
}

V4="$(fetch "$V4_URL")"
V6="$(fetch "$V6_URL")"

# A truncated or empty download must never silently produce a file that trusts nothing (which
# breaks real-IP restoration) or, worse, a half-written one.
if [ -z "$V4" ] || [ -z "$V6" ]; then
  echo "refusing to write: empty range list from the upstream source" >&2
  exit 1
fi

{
  echo "# Generated by deploy/nginx/update-cloudflare-realip.sh — do not edit by hand."
  echo "# Source: $V4_URL and $V6_URL"
  echo "# Fetched: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  while read -r cidr; do [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"; done <<< "$V4"
  while read -r cidr; do [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"; done <<< "$V6"
  echo
  echo "# Only consulted for peers listed above; ignored for any other client."
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

install -m 0644 "$TMP" "$OUT"
echo "wrote $OUT ($(grep -c set_real_ip_from "$OUT") ranges trusted)"
